name: Multi CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install Dependencies
      run: |
        apt install wget cmake make -y
        wget https://apt.llvm.org/llvm.sh
        bash llvm.sh 17 all
      
    - name: Build
      env: 
        CXX: clang++-17
      run: |
        cmake .
        make
    
    - name: Run Unit Tests
      run: test/tests --gtest_output=xml:test_result.xml
    
    - name: Test reports  
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with: 
        path: test_result.xml


    - name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        path: ./cache
        key: microbench
    
    - name: Run Benchmarks
      run: microbench/microbench --benchmark_format=json | tee benchmark_result.json

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'googlecpp'
        output-file-path: benchmark_result.json
        external-data-json-path: ./cache/benchmark-data.json